spring:
  data:
    redis:
      host: ${REDIS_HOST_FT}
      port: ${REDIS_PORT_FT}
      password: ${REDIS_PASSWORD_FT}
rate-limit:
  email:
    capacity:
      standard: 20
      high: 50
    interval-in-minutes: 1
test-url: ${TEST_URL:http://localhost:8081}
