server:
  port: 8081

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        app-id-uri: ${APP_URI}
        authorization-clients:
          dataManagementApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${DATA_MANAGEMENT_AZ_API}/.default
          channelManagementApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${CHANNEL_MANAGEMENT_AZ_API}/.default
          subscriptionManagementApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${SUBSCRIPTION_MANAGEMENT_AZ_API}/.default
          accountManagementApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${ACCOUNT_MANAGEMENT_AZ_API}/.default
  config:
    import: "optional:configtree:/mnt/secrets/pip-ss-kv/"
  application:
    name: PIP Publication Services

service-to-service:
  data-management: ${DATA_MANAGEMENT_URL:https://pip-data-management.staging.platform.hmcts.net}
  channel-management: ${CHANNEL_MANAGEMENT_URL:https://pip-channel-management.staging.platform.hmcts.net}
  subscription-management: ${SUBSCRIPTION_MANAGEMENT_URL:https://pip-subscription-management.staging.platform.hmcts.net}
  account-management: ${ACCOUNT_MANAGEMENT_URL:https://pip-account-management.staging.platform.hmcts.net}

notify:
  api:
    key: ${NOTIFY_API_KEY:testingApiKey}
  links:
    subscription-page-link: ${NOTIFY_LINK_SUBSCRIPTION_PAGE:https://pip-frontend.staging.platform.hmcts.net/subscription-management}
    start-page-link: ${NOTIFY_LINK_START_PAGE:https://pip-frontend.staging.platform.hmcts.net}
    aad-sign-in-page-link: ${NOTIFY_LINK_AAD_SIGNIN_LINK:https://pip-frontend.staging.platform.hmcts.net/login?p=B2C_1_SignInUserFlow}
    aad-admin-sign-in-page-link: ${NOTIFY_LINK_AAD_ADMIN_SIGNIN_LINK:https://pip-frontend.staging.platform.hmcts.net/admin-dashboard}
    gov-guidance-page-link: ${NOTIFY_LINK_GOV_GUIDANCE:https://www.gov.uk}
    aad-pw-reset-link-admin: ${NOTIFY_LINK_AAD_RESET_PW_LINK_ADMIN:https://sign-in.pip-frontend.staging.platform.hmcts.net/pip-frontend.staging.platform.hmcts.net/oauth2/v2.0/authorize?p=B2C_1A_PASSWORD_RESET&client_id=cae650ba-431b-4fc8-be14-22d476ebd31b&nonce=defaultNonce&redirect_uri=https://pip-frontend.staging.platform.hmcts.net/password-change-confirmation/true&scope=openid&response_type=code&prompt=login&response_mode=form_post}
    aad-pw-reset-link-media: ${NOTIFY_LINK_AAD_RESET_PW_LINK_MEDIA:https://sign-in.pip-frontend.staging.platform.hmcts.net/pip-frontend.staging.platform.hmcts.net/oauth2/v2.0/authorize?p=B2C_1A_PASSWORD_RESET&client_id=cae650ba-431b-4fc8-be14-22d476ebd31b&nonce=defaultNonce&redirect_uri=https://pip-frontend.staging.platform.hmcts.net/password-change-confirmation/false&scope=openid&response_type=code&prompt=login&response_mode=form_post}
    media-verification-page-link: ${MEDIA_VERIFICATION_PAGE_LINK:https://pip-frontend.staging.platform.hmcts.net/media-verification?p=B2C_1_SignInMediaVerification}
    admin-dashboard-link: ${ADMIN_DASHBOARD_LINK:https://pip-frontend.staging.platform.hmcts.net/admin-dashboard}
    cft-sign-in-page-link: ${NOTIFY_CFT_SIGN_IN_LINK:https://pip-frontend.staging.platform.hmcts.net/cft-login}
  pi-team-email: ${PI_TEAM_EMAIL:teamEmail@email.com}

error-handling:
  num-of-retries: 3
  backoff: 2

third-party:
  certificate: ${THIRD_PARTY_CERTIFICATE:abcd}

envName: ${ENV_NAME:local}

springdoc:
  swagger-ui:
    path: /swagger-ui/

fileRetentionWeeks: 78 weeks
