server:
  port: 8081

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        app-id-uri: ${APP_URI}
        authorization-clients:
          dataManagementApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${DATA_MANAGEMENT_AZ_API}/.default
  config:
    import: "optional:configtree:/mnt/secrets/pip-ss-kv/"
  application:
    name: PIP Publication Services
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true
azure:
  application-insights:
    instrumentation-key: ${INSTRUMENTATION_KEY:00000000-0000-0000-0000-000000000000}

service-to-service:
  data-management: ${DATA_MANAGEMENT_URL:https://pip-data-management.staging.platform.hmcts.net}

notify:
  api:
    key: ${NOTIFY_API_KEY:testingApiKey}
  links:
    subscription-page-link: ${NOTIFY_LINK_SUBSCRIPTION_PAGE:https://pip-frontend.staging.platform.hmcts.net/subscription-management}
    start-page-link: ${NOTIFY_LINK_START_PAGE:https://pip-frontend.staging.platform.hmcts.net}
    aad-sign-in-page-link: ${NOTIFY_LINK_AAD_SIGNIN_LINK:https://pip-frontend.staging.platform.hmcts.net/login?p=B2C_1_SignInUserFlow}
    aad-admin-sign-in-page-link: ${NOTIFY_LINK_AAD_ADMIN_SIGNIN_LINK:https://pip-frontend.staging.platform.hmcts.net/admin-dashboard}
    gov-guidance-page-link: ${NOTIFY_LINK_GOV_GUIDANCE:https://www.gov.uk}
    aad-pw-reset-link: ${NOTIFY_LINK_AAD_RESET_PW_LINK:https://sign-in.pip-frontend.staging.platform.hmcts.net/pip-frontend.staging.platform.hmcts.net/oauth2/v2.0/authorize?p=B2C_1A_DEMO_PASSWORDRESET_ACCOUNTEXISTS&client_id=cae650ba-431b-4fc8-be14-22d476ebd31b&nonce=defaultNonce&redirect_uri=https://pip-frontend.staging.platform.hmcts.net%2Fpassword-change-confirmation&scope=openid&response_type=id_token&prompt=login}
    media-verification-page-link: ${MEDIA_VERIFICATION_PAGE_LINK:https://pip-frontend.staging.platform.hmcts.net/media-verification?p=B2C_1_SignInMediaVerification}
    admin-dashboard-link: ${ADMIN_DASHBOARD_LINK:https://pip-frontend.staging.platform.hmcts.net/admin-dashboard}
  pi-team-email: ${PI_TEAM_EMAIL:teamEmail@email.com}

error-handling:
  num-of-retries: 3
  backoff: 2

third-party:
  certificate: ${THIRD_PARTY_CERTIFICATE:abcd}
