spring:
  cloud:
    azure:
      active-directory:
        enabled: false
  autoconfigure:
    exclude:
      - "org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration"
      - "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"
