openapi: 3.0.0
info:
  title: Publication Service
  description: This is the publication service
  version: 0.0.1
paths:
  /:
    summary: Root GET endpoint
    get:
      description: Root GET endpoint
      summary: Returns Welcome to spring-boot-template
      responses:
        '200':
          description: 'Hello Response'
          content:
            text/plain:
              schema:
                type: string
  /publication:
    summary: Dummy endpoint to demontrate how global exception handling works
    get:
      description: Dummy endpoint that describes how global exception handling works
      summary: Dummy endpoint
      responses:
        '200':
          description: 'Publication not found'
          content:
            text/plain:
              schema:
                type: string
