java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    pip-shared-kv-dev: 
      excludeEnvironmentSuffix: false
      resourceGroup: pip-sharedservices-dev-rg
      usePodIdentity: true
      secrets:
        - gov-uk-notify-api-testing-key
  environment:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: pip-shared-kv-dev
          key: gov-uk-notify-api-testing-key